import type { Metadata } from "next";
import "./globals.css";
import { Oswald, Source_Sans_3 } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Cyclone",
  description: "Generated by Cyclone",
};

// Import font Oswald with weight 400, 600, and 700
const oswald = Oswald({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald",
});

// Import font Source Sans 3 with weight 400, 600, and 700
const sourceSans = Source_Sans_3({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/assets/logo_cyclone.png"
          sizes="32x32"
          type="image/png"
        />
      </head>
      <body className={`${oswald.variable} ${sourceSans.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
